# Generated by Django 5.2.8 on 2026-02-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="projects/advanced/")),
                ("urls", models.URLField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="IntermediateProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="projects/intermediate/")),
                ("urls", models.URLField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="beginnerproject",
            name="images",
            field=models.ImageField(upload_to="projects/beginner/"),
        ),
        migrations.AlterField(
            model_name="beginnerproject",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
